[CmdletBinding(SupportsShouldProcess=$true)]
param([Parameter(Mandatory=$true)][string]$PackageRoot,[Parameter(Mandatory=$true)][string]$ProjectRoot,[ValidateSet('Upgrade')][string]$Mode='Upgrade')
$ErrorActionPreference='Stop'
$preflight=Join-Path $PackageRoot 'scripts/Test-CommandCenterNarrowViewportResponsiveClosureV1Preflight.ps1'
& $preflight -ProjectRoot $ProjectRoot -PackageRoot $PackageRoot
$relativeFiles=@('backend/src/palwakf_local_agents/command_center/static/index.html','backend/src/palwakf_local_agents/command_center/static/styles.css','backend/src/palwakf_local_agents/command_center/static/app.js')
$stamp=Get-Date -Format 'yyyyMMddHHmmss';$backup=Join-Path $ProjectRoot "backups/command_center_narrow_viewport_responsive_closure_v1_$stamp"
if($WhatIfPreference){foreach($relative in $relativeFiles){"What if: Performing the operation `"Backup command-center static preimage`" on target `"$(Join-Path $ProjectRoot $relative)`""};foreach($relative in $relativeFiles){"What if: Performing the operation `"Install command-center responsive static asset`" on target `"$(Join-Path $ProjectRoot $relative)`""};'INSTALL_STATUS=WHATIF_COMPLETE';"BACKUP_PATH=$backup";'BACKUP_STATUS=PLANNED'}else{New-Item -ItemType Directory -Path $backup -Force|Out-Null;foreach($relative in $relativeFiles){$target=Join-Path $ProjectRoot $relative;$backupTarget=Join-Path $backup $relative;New-Item -ItemType Directory -Path (Split-Path $backupTarget -Parent) -Force|Out-Null;Copy-Item -LiteralPath $target -Destination $backupTarget -Force};$manifest=@{batch='COMMAND_CENTER_NARROW_VIEWPORT_RESPONSIVE_CLOSURE_V1';created_at=(Get-Date).ToString('o');files=@{}};foreach($relative in $relativeFiles){$manifest.files[$relative]=(Get-FileHash -LiteralPath (Join-Path $ProjectRoot $relative) -Algorithm SHA256).Hash};$manifest|ConvertTo-Json -Depth 5|Set-Content -LiteralPath (Join-Path $backup 'install_preimage_manifest.json') -Encoding UTF8;foreach($relative in $relativeFiles){$source=Join-Path $PackageRoot $relative;$target=Join-Path $ProjectRoot $relative;Copy-Item -LiteralPath $source -Destination $target -Force};'INSTALL_STATUS=COMPLETE';"BACKUP_PATH=$backup";"BACKUP_MANIFEST_PATH=$(Join-Path $backup 'install_preimage_manifest.json')";'BACKUP_STATUS=COMPLETE'}
'TARGET_MUTATION_SCOPE=COMMAND_CENTER_STATIC_ASSETS_ONLY';'APP_ENTRYPOINT_MUTATION=NONE';'API_MUTATION=NONE';'GOVERNED_OPERATIONS_MUTATION=NONE';'WORKSPACE_CORE_MUTATION=NONE';'LOCAL_SQLITE_WRITE=NONE_DURING_INSTALL';'MODEL_EXECUTION=NONE';'PILOT_EXECUTION=NOT_EXECUTED'
